### PR TITLE
'vmc target' checks the /info on the old target not the new one

### PR DESCRIPTION
**Pull request by dsyer**
```
$ vmc target api.vcap.me
$ vmc info
... shutdown vcap.me
$ vmc target api.cloudfoundry.com
CFoundry::TargetRefused: target refused connection (Connection refused - connect(2))
For more information, see ~/.vmc/crash
```

If you switch on --trace you can see that vmc sends a GET to /info on the _old_ target as the first step in changing the target.  Looks like a bug (and a newish one - it worked fine with 0.4.7).

I'm using 0.5.0.rc1.

### CODE REVIEW

**Comment by cf-frontend** [comment]
Try with rc2; I think we fixed this already.
- Alex & Dennis

**Comment by dsyer** [comment]
I can't see any changes to cli.rb since this one in hithub master (up to rc2).  Can you clarify how it was fixed and how I can get access to the code to try it?  Here's a stack trace from rc2 showing the same behaviour:

```
 $ vmc target api.cloudfoundry.com --trace
Setting target to https://api.cloudfoundry.com>>>.  
REQUEST: GET https://ccng.cf84.dev.las01.vcsops.com/info
REQUEST_HEADERS:
  Accept : application/json
  Authorization : bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJkMjY5YWFhNS1iODlmLTRhMGQtOTY4Mi1kYjYyMTk3N2VmYzgiLCJ1c2VyX2lkIjoiODZjNDZiZjgtNjc3ZS00ZWFjLTg3ZGItMGI3ZjJmMjdmODVmIiwic3ViIjoiODZjNDZiZjgtNjc3ZS00ZWFjLTg3ZGItMGI3ZjJmMjdmODVmIiwidXNlcl9uYW1lIjoic3JlQHZtd2FyZS5jb20iLCJlbWFpbCI6InNyZUB2bXdhcmUuY29tIiwic2NvcGUiOlsic2NpbS5yZWFkIiwiY2xvdWRfY29udHJvbGxlci5hZG1pbiIsInBhc3N3b3JkLndyaXRlIiwic2NpbS53cml0ZSIsImNsb3VkX2NvbnRyb2xsZXIud3JpdGUiLCJvcGVuaWQiLCJjbG91ZF9jb250cm9sbGVyLnJlYWQiXSwiY2xpZW50X2lkIjoidm1jIiwiY2lkIjoidm1jIiwiaWF0IjoxMzYyMDY1OTY2LCJleHAiOjEzNjIxMDkxNjYsImlzcyI6Imh0dHBzOi8vdWFhLmNmODQuZGV2LmxhczAxLnZjc29wcy5jb20vb2F1dGgvdG9rZW4vb2F1dGgvdG9rZW4iLCJhdWQiOlsic2NpbSIsIm9wZW5pZCIsImNsb3VkX2NvbnRyb2xsZXIiLCJwYXNzd29yZCJdfQ.mH0LPBBp-FHrixlYQINsx7AujMjb1ZONd5y2ZGEYatM
  Content-Length : 0
... FAILED
CFoundry::TargetRefused: target refused connection (getaddrinfo: Name or service not known)
For more information, see ~/.vmc/crash
```

**Comment by andreacampi** [comment]
Seconded, I'm seeing the same with rc2.

**Comment by cf-frontend** [comment]
Confirmed it, we were thinking of a different issue. Story is in the backlog to be fixed soon.

**Comment by cf-frontend** [comment]
We have fixed this in 16edbbdd19b0dd6ca7c4aa7041c57917def13845, which will be included in the next release candidate. Please let us know if you have any issues.
- Chris & Sheel

**Pull request closed without merging**
